[package]
name = "mysteriouspants-esiweblogin"
version = "0.0.1"
publish = false

[dependencies]
gotham = "0.4.0"
gotham_derive = "0.4.0"
hyper = "0.12.35"
mime = "0.3.14"
mysteriouspants-esi = { path = "../../esirs" }
serde = "1.0.101"
serde_derive = "1.0.101"
toml = "0.5.3"