[package]
name = "mysteriouspants-esiweblogin"
version = "0.0.1"
publish = false

[dependencies]
gotham = "*"
gotham_derive = "*"
hyper = "*"
mime = "*"
mysteriouspants-esi = { path = "../../esirs" }
serde = "*"
serde_derive = "*"
toml = "*"